fix: gitleaks errors in macos

diff --git a/.azurepipelines/test-pipeline.yaml b/.azurepipelines/test-pipeline.yaml
--- a/.azurepipelines/test-pipeline.yaml
+++ b/.azurepipelines/test-pipeline.yaml
@@ -496,17 +496,24 @@ jobs:
           set -e
           echo "Running Gitleaks for secret detection..."
           GITLEAKS_VERSION="8.21.2"
-          echo "Installing Gitleaks version: $GITLEAKS_VERSION"
-          curl -sSfL "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz" | tar -xz -C /tmp  # yamllint disable-line rule:line-length
 
+          if [[ "$(uname)" == "Darwin" ]]; then
+            PLATFORM="darwin_x64"
+          else
+            PLATFORM="linux_x64"
+          fi
+
+          echo "Installing Gitleaks version: $GITLEAKS_VERSION for $PLATFORM"
+          curl -sSfL "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_${PLATFORM}.tar.gz" | tar -xz -C /tmp # yamllint disable-line rule:line-length
           chmod +x /tmp/gitleaks
           /tmp/gitleaks detect --source . --report-format json --report-path gitleaks-report.json || {
-          echo "Gitleaks found secrets or encountered an error. See gitleaks-report.json for details."
-          cat gitleaks-report.json
-          exit 1
+            echo "Gitleaks found secrets or encountered an error. See gitleaks-report.json for details."
+            cat gitleaks-report.json
+            exit 1
           }
         displayName: "Run Gitleaks - secret detection"
         condition: ne(variables['Agent.OS'], 'Windows_NT')
+
 
       - task: PowerShell@2
         displayName: "Run Gitleaks [Windows]"
